# Generated by Django 2.0.7 on 2019-06-02 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190530_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUploadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('type', models.CharField(choices=[('Accommodation-Room-Allocation', 'Accommodation-Room-Allocation'), ('Accommodation-Room-Allocation', 'Accommodation-Room-Allocation')], max_length=255)),
                ('total_processing', models.IntegerField()),
                ('total_success', models.IntegerField()),
                ('total_failure', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
