# Generated by Django 2.0.7 on 2019-06-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190604_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportationpickuplocation',
            name='location',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
