# Generated by Django 2.0.7 on 2019-06-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190604_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationpickuplocation',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
            preserve_default=False,
        ),
    ]
