# Generated by Django 2.0.7 on 2019-06-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_transportationpickuplocation_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
