# Generated by Django 2.0.7 on 2019-06-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190607_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitemgroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='eventitemgroup',
            unique_together={('event', 'name')},
        ),
    ]
