# Generated by Django 2.0.7 on 2019-06-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20190609_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventitemgroup',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
