# Generated by Django 2.0.7 on 2019-05-28 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('coupon_code', models.CharField(max_length=64, unique=True)),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=19)),
                ('amount_used', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('type', models.CharField(choices=[('Discount-Coupon', 'Discount-Coupon'), ('Credit-Coupon', 'Credit-Coupon'), ('Debit-Coupon', 'Debit-Coupon'), ('Senior-Citizen-Discount', 'Senior-Citizen-Discount')], max_length=32)),
                ('status', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_operator', to=settings.AUTH_USER_MODEL)),
                ('item_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.ItemMaster')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_operator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
