# Generated by Django 2.0.7 on 2019-05-28 10:12

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
        ('coupons', '__first__'),
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('period_from', models.DateTimeField()),
                ('period_to', models.DateTimeField()),
                ('cancellation_per', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('event_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.EventItem')),
                ('item_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.ItemMaster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('order_number', models.IntegerField(default=0)),
                ('order_cfy', models.CharField(max_length=32)),
                ('transaction_type', models.CharField(choices=[('e-registration', 'e-registration')], max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('balance_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('web_initiated', models.BooleanField(default=False)),
                ('app_initiated', models.BooleanField(default=False)),
                ('one_time_password', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, max_length=2000)),
                ('delivery_access', models.CharField(blank=True, max_length=255)),
                ('order_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_orders', to='events.Event')),
                ('event_attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_registration', to='events.EventAttendee')),
                ('event_registration_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.EventRegistrationType')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='OrderCfyAndOrderNumberTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('latest_order_number', models.IntegerField(default=1)),
                ('latest_order_cfy', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('deleted_by', models.IntegerField(null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('order_number', models.IntegerField()),
                ('order_cfy', models.CharField(max_length=32)),
                ('transaction_type', models.CharField(choices=[('Sale', 'Sale'), ('Cancel', 'Cancel'), ('Receipt', 'Receipt'), ('Refund', 'Refund'), ('Coupon', 'Coupon'), ('Balance', 'Balance'), ('Self Transfer', 'Self Transfer'), ('Item-Tax-Or-Service-Charge', 'Item-Tax-Or-Service-Charge'), ('Cancellation-Charge', 'Cancellation-Charge')], max_length=255)),
                ('transaction_reference_id', models.CharField(blank=True, max_length=255)),
                ('privileged', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=19)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=19)),
                ('item_sc', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('amount_taxable', models.DecimalField(decimal_places=2, max_digits=19)),
                ('item_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('amount_final', models.DecimalField(decimal_places=2, max_digits=19)),
                ('is_coupon_item', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('actual_item_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_item_master', to='items.ItemMaster')),
                ('canceled_ordered_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_reference', to='orders.OrderedItem')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.Coupon')),
                ('event_attendee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.EventAttendee')),
                ('event_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.EventItem')),
                ('item_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_orders', to='items.ItemMaster')),
                ('parent_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderedItem')),
                ('transportation_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.TransportationInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='orders.OrderedItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='previous_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
